### ISSUE TITLE
Sign up functionality

### ISSUE THREAD

**Issue by edmondpr** [MentorsWithoutBorders/mwb-partners-admin#11]
**Design:** https://www.figma.com/file/DgrKZX9mS13Zgf7k5pZ1WT/Partner-web-app?type=design&node-id=814-612&t=LPfyjEb31x9adSCp-4

The current signup process will be updated so that it takes into consideration the `is_mentor`, `is_org_manager`, `is_centre_manager` values from the `approved_users` table (users can only sign up if they are found in this table).

Currently, there is an onboarding process (https://onboarding.mentorswithoutborders.net) which populates the `approved_users` table, but for the organization managers and centre managers the values will be added manually (at least for now).

When the user presses the `Create account` button, the relevant permission will be added to the `admin_permissions` table, which also means that we won't have the `is_mentor` column in the `users` table anymore.

As a quick note, the column `has_mentors` from the `organizations` table tells us whether that organization is a partner company or a partner NGO.

**Comment by ManojBahuguna** [comment]
@edmondpr, wanted to confirm. Why not use `approved_users` table directly for _is_mentor/is_org_manager/is_centre_manager_, instead of copying those to `admin_permissions` on signup?

**Comment by edmondpr** [comment]
@ManojBahuguna, I would prefer to copy the values in the `admin_permissions` table because we can have the same `user_id` from the `users` table. I also always thought of the `approved_users` table as being a temporary one until the user signs up (currently the `is_mentor` property from this table is only being used during the sign up process).

**Comment by ManojBahuguna** [comment]
Understood. Thanks for the clarification.

**Comment by ManojBahuguna** [comment]
Created PR at https://github.com/MentorsWithoutBorders/mwb-connect-backend/pull/14

@edmondpr We can create a separate issue for removing `is_mentor` from Users table (and using from admin_permissions instead), since that change affects many existing queries as well.

**Comment by edmondpr** [comment]
@ManojBahuguna Sure, I'll actually create this task later on because it affects the mobile app as well.

**Comment by edmondpr** [comment]
@ManojBahuguna There are currently 2 issues:

- can't sign up when `is_org_manager` or `is_centre_manager` are TRUE in the `approved_users` table because it's asking for a goal, and that should only be the case when they are FALSE and `is_mentor` is also FALSE (having all 3 of them FALSE means that the user is a student)
- even if I enter a goal, `is_org_manager` or `is_centre_manager` being TRUE in `approved_users` doesn't translate to them being TRUE in the `admin_permissions` table as well.

**Comment by edmondpr** [comment]
For the second issue, please refer to my last 2 comments on this PR:
https://github.com/MentorsWithoutBorders/mwb-connect-backend/pull/14

**Comment by ManojBahuguna** [comment]
> For the second issue, please refer to my last 2 comments on this PR: [MentorsWithoutBorders/mwb-connect-backend#14](https://github.com/MentorsWithoutBorders/mwb-connect-backend/pull/14)

Hi Edmond, I am not seeing your comments on PR. Could you please check if they were submitted?

**Comment by edmondpr** [comment]
Sorry, I just noticed that my last comments don't appear at the bottom of that page. I was referring to these 2 comments:
"The `is_org_manager` and `is_centre_manager` values are not present in the `getApprovedUserQuery` so they will always be null here."
"Since `approvedUser` is passed as a parameter to the function `adminPermissions.addPermission`, I think the `Permissions` and `AdminPermission` models won't be necessary as they are not being used anywhere else."
