### ISSUE TITLE
Date input field

### ISSUE THREAD

**Issue by edmondpr** [MentorsWithoutBorders/mwb-partners-admin#20]
The date input field component will have a calendar icon inside, on the left-hand side (e.g. https://www.figma.com/file/DgrKZX9mS13Zgf7k5pZ1WT/Partner-web-app?type=design&node-id=727-4&t=mbtHE6BqgQ0at0fH-4). 

When clicking inside the date input field, a date selector should appear underneath.

**Comment by ugudlado** [comment]
@ManojBahuguna I picked this up as it was there in Todo column.

**Comment by edmondpr** [comment]
@ugudlado Please check with @ManojBahuguna as he had already started implementing the [MUI date picker](https://mui.com/x/react-date-pickers/date-picker/) for this component.

**Comment by ugudlado** [comment]
@edmondpr Sure. I was looking at the same as well. I picked based on Todo column in the project. 

@ManojBahuguna Please confirm if you already started on this and will pick up something tomorrow accordingly.

**Comment by ManojBahuguna** [comment]
Hi @ugudlado. Yes, I plan to work on it this weekend. Will update the status on board.
Please feel free to make any suggestions.
Thanks
