### ISSUE TITLE
Dashboard - stats for partner NGOs

### ISSUE THREAD

**Issue by edmondpr** [MentorsWithoutBorders/mwb-partners-admin#43]
**Design:** https://www.figma.com/file/DgrKZX9mS13Zgf7k5pZ1WT/Partner-web-app?type=design&node-id=727-66&mode=design&t=IrpaeVusdRlOAZoD-4

If the logged in user is a from a partner NGO, the following data will be made available:

- total number of students from the partner NGO who have enrolled in at least one course and who haven't cancelled it
- total number of courses in which the students from the partner NGO have enrolled (completed + not completed)
- total number of hours until the current date, corresponding to the lessons that haven't been cancelled in the courses (1h per lesson)

The data will be made available on the `/api/v1/partners/{partner_id}/dashboard/stats` endpoint.

If the view mode is set to `All MWB participants`, the endpoint will be `/api/v1/partners/dashboard/stats`.

The results will take into consideration the selected year and the view mode (data for own organization / all MWB participants).

**Comment by ManojBahuguna** [comment]
@edmondpr, could you please confirm permission requirements for these APIs?
- `/partners/{partner_id}/dashboard/stats` - users who are part of provided organization (partner_id) can access
- `/partners/dashboard/stats` - users who are part of **_any_** organization can access the stats

**Comment by edmondpr** [comment]
@ManojBahuguna, the permissions that you've mentioned are correct but more than that, the 2 endpoints are about displaying the stats for the logged in organization or for all organizations.
