### ISSUE TITLE
Mentors table - stats

### ISSUE THREAD

**Issue by edmondpr** [MentorsWithoutBorders/mwb-partners-admin#50]
**Design:** https://www.figma.com/file/DgrKZX9mS13Zgf7k5pZ1WT/Partner-web-app?type=design&node-id=727-2&mode=design&t=rESN2vPU0w6pDYKl-4

If the logged in user is a from a partner company, the following data will be made available:

- total number of mentors from the partner company who have scheduled at least 1 course
- total number of students who have enrolled in the courses scheduled by the mentors from the partner company and who haven't cancelled their courses
- total number of courses scheduled by the mentors (completed + not completed)
- total number of hours corresponding to the lessons that haven't been cancelled in the courses (1h per lesson)

The data will be made available on the `/api/v1/partners/{partner_id}/mentors/stats` endpoint.

The results will take into consideration the search term and the selected date range (passed in the body of the API request).

**Comment by ugudlado** [comment]
@tahir-shahzad4 / @edmondpr 
Created this PR: https://github.com/MentorsWithoutBorders/mwb-connect-backend/pull/21

**Comment by ugudlado** [comment]
@edmondpr / @tahir-shahzad4 Considering pull request merged, closing this ticket.
