### ISSUE TITLE
Students table - stats

### ISSUE THREAD

**Issue by edmondpr** [MentorsWithoutBorders/mwb-partners-admin#53]
**Design:** https://www.figma.com/file/DgrKZX9mS13Zgf7k5pZ1WT/Partner-web-app?type=design&node-id=727-182&mode=design&t=rESN2vPU0w6pDYKl-4

If the logged in user is a from a partner NGO, the following data will be shown:

- total number of students from the partner NGO who have enrolled in at least one course and who haven't cancelled it
- total number of courses in which the students from the partner NGO have enrolled (completed + not completed)
- total number of hours corresponding to the lessons that haven't been cancelled in the courses (1h per lesson)

The data will be retrieved from the `/api/v1/partners/{partner_id}/students/stats` endpoint.

The results will take into consideration the selected centre ID, the search term and the selected date range (passed in the body of the API request).

**Comment by Mohmed-Refaay** [comment]
@edmondpr I think this is already implemented by @ManojBahuguna.

**Comment by edmondpr** [comment]
@Mohmed-Refaay You're right, I've moved it to done now.
