### ISSUE TITLE
Mentors table - list of company projects

### ISSUE THREAD

**Issue by edmondpr** [MentorsWithoutBorders/mwb-partners-admin#55]
**Design:** https://www.figma.com/file/DgrKZX9mS13Zgf7k5pZ1WT/Partner-web-app?type=design&node-id=1230-7182&mode=design&t=hBrWoc8WQXwB3NIH-4

The `/api/v1/partners/{partner_id}/projects` endpoint will return the list of company projects from the `projects` table.

**Comment by ugudlado** [comment]
I am working on it. I am still not able to assign to myself. So, putting in comment here.

cc @tahir-shahzad4 @edmondpr

**Comment by ugudlado** [comment]
@edmondpr / @tahir-shahzad4 Created this PR: https://github.com/MentorsWithoutBorders/mwb-connect-backend/pull/20

**Comment by ugudlado** [comment]
@edmondpr / @tahir-shahzad4 Considering pull request merged, closing this ticket.
