### ISSUE TITLE
Mentors table - add company project

### ISSUE THREAD

**Issue by edmondpr** [MentorsWithoutBorders/mwb-partners-admin#56]
**Design:** https://www.figma.com/file/DgrKZX9mS13Zgf7k5pZ1WT/Partner-web-app?type=design&node-id=1230-7182&mode=design&t=hBrWoc8WQXwB3NIH-4

New projects can be added by calling the `/api/v1/partners/{partner_id}/projects` endpoint.

**Comment by ugudlado** [comment]
I started working on this

**Comment by ugudlado** [comment]
PR got merged. Closing this ticket.
