### ISSUE TITLE
Mentors table - projects dropdown

### ISSUE THREAD

**Issue by edmondpr** [MentorsWithoutBorders/mwb-partners-admin#57]
**Design:** https://www.figma.com/file/DgrKZX9mS13Zgf7k5pZ1WT/Partner-web-app?type=design&node-id=1230-7182&mode=design&t=hBrWoc8WQXwB3NIH-4

When clicking on the projects dropdown, a list of projects will appear underneath.

The first option in the list will be `Create new project`.

The list of projects will be retrieved from the `/api/v1/partners/{partner_id}/projects` endpoint.

**Comment by ugudlado** [comment]
@Mohmed-Refaay completed this.
